version: '3.8'

services:
  backend:
    build: ./backend
    container_name: detective-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
    environment:
      - MONGODB_URL=${MONGODB_URL}
      - DB_NAME=todays_detective
    networks:
      - detective-network

networks:
  detective-network:
    driver: bridge
